HelpDesk.UI/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDesk.Common.Entities;
using HelpDesk.UI.Data;
using HelpDesk.UI.Repiostry;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Authorization;

namespace HelpDesk.UI.Controllers
{
    [Authorize]
    public class AgentsController : Controller
    {
        private readonly AppDbContext _context;

       
        

        public AgentsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: UserDetails
        public async Task<IActionResult> Index()
        {
            UserRep item=new UserRep(_context);
            var appDbContext = item.get();
            return View(await appDbContext);
        }


        // GET: UserDetails/Create
        public async Task<IActionResult> Create(Guid? id)
        {
            UserRep item = new UserRep(_context);
            

            var userDetail = await item.AddorEdit(id);
            if (userDetail == null)
            {
                return NotFound();
            }
            ViewData["Companies"] = new SelectList(userDetail.Companylist, "Value", "Text", userDetail.CompanyId);
            return View(userDetail);
        }

        // POST: UserDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,Mobile,IsEnabled,Password,CompanyId")] UserDetail userDetail)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userDetail.Id = Guid.NewGuid();
                    _context.Add(userDetail);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(Exception ex) { 
                Console.Write(ex); 
            }

            ViewData["Companies"] = new SelectList(_context.companies, "CompanyId", "CompanyId", userDetail.CompanyId);
            return View(userDetail);
        }

        // GET: UserDetails/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            UserRep item = new UserRep(_context);
            if (id == null )
            {
                return NotFound();
            }
            Thread.Sleep(100);
            var userDetail = await item.AddorEdit(id);
            if (userDetail == null)
            {
                return NotFound();
            }
            ViewData["Companies"] = new SelectList(userDetail.Companylist,  "Value", "Text", userDetail.CompanyId);

           
            return View(userDetail);
        }

        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,FirstName,LastName,Email,Mobile,IsEnabled,Password,CompanyId")] UserDetail userDetail)
        {
            Thread.Sleep(100);
            if (id != userDetail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserDetailExists(userDetail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.companies, "CompanyId", "CompanyId", userDetail.CompanyId);
            return View(userDetail);
        }

        // GET: UserDetails/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.users == null)
            {
                return NotFound();
            }

            var userDetail = await _context.users
                .Include(u => u.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userDetail == null)
            {
                return NotFound();
            }

            return View(userDetail);
        }

        // POST: UserDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                if (_context.users == null)
                {
                    return Problem("Entity set 'AppDbContext.users'  is null.");
                }
                var userDetail = await _context.users.FindAsync(id);
                if (userDetail != null)
                {
                    _context.users.Remove(userDetail);
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.InnerException.Message.ToString());
            }
        }

        private bool UserDetailExists(Guid id)
        {
          return (_context.users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HelpDesk.UI/Controllers/CustomersController.cs
using HelpDesk.Common.Entities;
using HelpDesk.Common.Models;
using HelpDesk.UI.Data;
using HelpDesk.UI.Repiostry;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Security.Claims;

namespace HelpDesk.UI.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private  AppDbContext _context;

         readonly CustomerRep _customerRep;
        public CustomersController(AppDbContext context)
        {
            _context = context;
            
        }
        public   void GetDrpDown()
        {
           
            ViewData["StateCode"] = new SelectList(_context.map.Where(x => x.AttributeName == "statecode"), "AttributeValue", "DisplayValue");
            ViewData["StatusCode"] = new SelectList(_context.map.Where(x => x.AttributeName == "statuscode"), "AttributeValue", "DisplayValue");
            ViewData["CaseTypeCode"] = new SelectList(_context.map.Where(x => x.AttributeName == "casetypecode"), "AttributeValue", "DisplayValue");
            ViewData["CaseOriginCode"] = new SelectList(_context.map.Where(x => x.AttributeName == "CaseOriginCode"), "AttributeValue", "DisplayValue");
            ViewData["PriorityCode"] = new SelectList(_context.map.Where(x => x.AttributeName == "PriorityCode"), "AttributeValue", "DisplayValue");
        }
        public async Task< IActionResult> Index()
        {
            CustomerRep rep = new CustomerRep(_context);



            var model = await rep.get();
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateCustomerModel customer)
        {
            if (ModelState.IsValid)
            {
            }
            return View(customer);


        }

        [HttpGet]
        public  async Task<IActionResult> Edit(string id)
        {
            if (!String.IsNullOrWhiteSpace(id))
            {
                bool isGuid = Guid.TryParse(id, out Guid customerId);
                if (isGuid && customerId != Guid.Empty)
                {

                    ViewData["Contacts"]=  new SelectList(_context.contacts, "ContactId", "FullName");

                    var model = await _context.customers.Select(e => new CustomerModel()
                    {
                        Id = customerId,
                        editCustomerModel = new EditCustomerModel()
                        {
                            CustomerId = e.CustomerId,
                            Name = e.Name,
                            PrimaryContactId = e.PrimaryContactId,
                            EmailAddress1 = e.EmailAddress1,
                            EmailAddress2 = e.EmailAddress2,
                            Telephone1 = e.Telephone1,
                            Telephone2 = e.Telephone2,
                            AccountNumber = e.AccountNumber,
                            OwnerId = e.OwnerId,
                        },
                        Incidentlist = e.Incidents.Select(i => new IncidentModel()
                       {
                            IncidentId = i.IncidentId,
                            Customer = i.Customer.Name,
                            Title = i.Title
                       }).ToList()

                    }).Where(e => e.Id == customerId).FirstOrDefaultAsync();
                    return View(model);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(string customerid, EditCustomerModel model)
        {
            CustomerRep rep = new CustomerRep(_context);
            if (ModelState.IsValid)
            {
                model.ModifiedBy = Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid)?.Value);
                bool IsSaved = rep.AddorEdit(Guid.Parse(customerid), model);
                return RedirectToAction(nameof(Index));
            }

           return View(model);
        }

        [HttpGet]
      public IActionResult CreateIncidentByCustomerId(string customerId)
        {
            if (!String.IsNullOrWhiteSpace(customerId))
            {
                bool isGuid = Guid.TryParse(customerId, out Guid _customerId);
                if (isGuid && _customerId != Guid.Empty)
                {
                    IncidentRep rep= new IncidentRep(_context);
                    var model = rep.GetCustomerId(_customerId);
                    ViewData["CustomerId"] = model.Customers;
                    GetDrpDown();
                    return View( model);
                }
            }
            return NotFound();

        }
        public IActionResult CreateIncidentByCustomerId(IncidentCreateModel model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedOn = DateTime.Now;
                model.OwnerId = Guid.Parse("55DD5AD7-6475-40C2-844D-EEC2068F0B0A");
                model.CreatedBy= Guid.Parse("55DD5AD7-6475-40C2-844D-EEC2068F0B0A");
                IncidentRep rep = new IncidentRep(_context);
                bool r = rep.Save(model);
                if (r)
                {
                    TempData["SuccessMessage"] = "Save Successful";
                }
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }



   }
}

HelpDesk.UI/Views/Shared/_BusyIndicatorPartial.cshtml
<div class="loading">
    Loading
</div>

<script>
    function displayBusyIndicator() {
        $('.loading').show();
    }
</script>

HelpDesk.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - HelpDesk.UI</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet" />
   
    <link href="~/lib/datatables/css/jquery.datatables.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelpDesk.UI.styles.css" asp-append-version="true" />
    
</head>
<body>
   
    <div id="wrapper">
    <header>
            <nav class="navbar navbar-expand-sm navbar-dark">
                <a class="navbar-brand" href="#">
                    <img id="logo" src="https://i.imgur.com/K7Nwq4V.jpg"> Acme Inc
                    </a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active"  asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Incidents" asp-action="Index">Incidents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Agents" asp-action="Index">Agent</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
                
            </nav>
        
    
    </header>
   <main class="container-fluid min-vh-80">
            <partial name="_BusyIndicatorPartial" />
            @RenderBody()
            
    </main>
        <footer>

            <div class="bg-black py-2">
                <div class="container text-center">
                    <p class="text-muted mb-0 py-2">© 2019 Onkar All rights reserved.</p>
                </div>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
        <script src="~/lib/datatables/js/datatables.bootstrap4.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

HelpDesk.UI/Views/Shared/_buttonList.cshtml
<div class="card-footer">
    <div class="col-md-12 d-flex justify-content-between">

    
    <button type="submit" class="btn btn-secondary" asp-action="index">Cancel</button>
   
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</div>